[tools]
bun = "1.2.18"

[tasks.dev]
run = "bun --bun run dev"

[tasks.format]
run = "bun --bun run biome format --write ."

[tasks.lint]
run = "bun --bun run oxlint"

[tasks.typecheck]
run = "bun --bun run tsc"

[tasks.test]
run = "bun test"

[tasks.build]
run = "bun build --compile --minify --bytecode --outfile=bin/color-convert index.ts"

[tasks.build-npm]
run = [
  "mkdir -p bin",
  "bun build index.ts --outfile=bin/color-convert.js --target=node",
  "echo '#!/usr/bin/env node' | cat - bin/color-convert.js > temp && mv temp bin/color-convert.js",
  "chmod +x bin/color-convert.js",
]

[tasks.check]
run = [
  "mise run format",
  "mise run lint",
  "mise run typecheck",
  "mise run test",
]

[tasks.release]
run = "bun run release.ts"

[tasks.publish]
run = ["mise run check", "mise run build-npm", "npm publish"]
