[tools]
bun = "1.2.18"

[tasks.dev]
run = "bun --bun run dev"

[tasks.format]
run = "bun --bun run biome format --write ."

[tasks.lint]
run = "bun --bun run oxlint"

[tasks.typecheck]
run = "bun --bun run tsc"

[tasks.test]
run = "bun test"

[tasks.build-npm]
run = [
  "mkdir -p dist",
  "bun build index.ts --outfile=dist/cast.js --target=node",
  "echo '#!/usr/bin/env node' | cat - dist/cast.js > temp && mv temp dist/cast.js",
  "chmod +x dist/cast.js",
]

[tasks.check]
run = [
  "mise run format",
  "mise run lint",
  "mise run typecheck",
  "mise run test",
]

[tasks.release]
depends = ["check"]
run = "bun run release.ts"

[tasks.publish]
depends = ["release"]
run = ["mise run build-npm", "npm publish"]
